spring.application.name=job-alert-massive-default
logging.level.hello=INFO
logging.level.org.springframework.ws=DEBUG
server.port=31795
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${SECRETS_URL_DB}
spring.datasource.username=${SECRETS_USER_DB}
spring.datasource.password=${SECRETS_PASSWORD_DB}
url-api-security-data-inquiry=http://security-data-inq-service:31731
#---ACIFUENTES 2025 RECOMENDACIÓN SONAR
file.paths.daily=/data/alertas_paycentral/billpay_C_YYYYMMDD.txt
file.paths.inactivate=/data/alertas_paycentral/billpay_I_YYYYMMDD.txt
#---SWAGGER ACIFUENTES 2025 
springdoc.swagger-ui.path=/alert/massive/default/swagger-ui
springdoc.api-docs.path=/alert/massive/default/v3/api-docs
# Forzar Swagger UI a usar la ruta correcta del JSON
springdoc.swagger-ui.url=/alert/massive/default/v3/api-docs